### ISSUE TITLE
Links in schedule not working?

### ISSUE THREAD

**Issue by a11n** [droidcon/gitbook-2015-berlin-barcamp#12]
The links in the schedule are not working for me, neither in the web representation nor in the PDF.

Web presentation leads to 404 (at least for most of the links I've tested):
http://droidcon.gitbooks.io/2015-berlin-barcamp/content/schedule.html

PDF links are not clickable but marked as link correctly.
https://www.gitbook.com/download/pdf/book/droidcon/2015-berlin-barcamp

Adding the *.md suffix to the links will solve the issue for the web presentation. But you mentioned there are any issue with this solution?

**Comment by friedger** [comment]
Should be fixed by https://github.com/droidcon/gitbook-2015-berlin-barcamp/commit/9b3beddf8912e2ef2fea86fd428fa6d5f042f652

Make sure to reload the schedule page not from cache

**Comment by friedger** [comment]
Thanks for the issue reporting!
